Add autoscaling metrics based on queue depth
blacksmith-community/rabbitmq-forge-boshrelease pull request #26
Opened 2022-06-09 15:24 UTC by itsouvalas

The proposed changes allow for standalone rmq service to be deployed with:  
* [rabbitmq-metrics-emitter-release](https://github.com/starkandwayne/rabbitmq-metrics-emitter-release) along with its dependencies 
* [bpm-release](https://github.com/cloudfoundry/bpm-release) and 
* [loggregator-agent-release](https://github.com/cloudfoundry/loggregator-agent-release).

Summary
* It depends on `blacksmith_services_ca` CA certificate which is created with [blacksmith-boshrelease](https://github.com/blacksmith-community/blacksmith-boshrelease/pull/18). 
* It creates a number of `meta` values and certificate `variables` that are fed conveniently  as jobs properties. 
* It creates a number of certificate template files which are populated through properties

2022-06-09 15:53 UTC, wayneeseguin requested changes
A few naming cleanup items but overall looks good.

2022-06-09 15:53 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/spec
> +    description: The private key for metrics emitter
Question: why do we need the private key for these vs just the server cert/ca?

2022-06-09 15:53 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +    password:   <%= p('cf.password') %>
Shouldn't this come from the `meta.yml` merge and not be in here?

2022-06-09 15:53 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +          ca: (( file "/var/vcap/jobs/blacksmith/config/tls/blacksmith_services_ca" ))
This is good, consistent with the single BS Services CA

2022-06-09 15:53 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +        - domain: "_.rabbitmq_standalone.bosh"
`_satandalone` has no value here, `_.rabbitmq.bosh` would be better.

2022-06-09 15:53 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/templates/tls/blacksmith_rabbitmq_services.ca
> +<%= p('blacksmith_rabbitmq_services.tls.ca_cert') %>
`blacksmith.ca_cert` ?

2022-06-10 12:57 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/spec
> +  tls/blacksmith_rabbitmq_services.ca:  tls/blacksmith_rabbitmq_services.ca
This was a remnant of the transition between CAs. Was removed in favour of https://github.com/blacksmith-community/blacksmith-boshrelease/pull/18. The `loggregator.ca` is the one provided by Cloudfoundry whereas the `rabbitmq.ca` gets populated by the file property on the standalone manifest [here](https://github.com/itsouvalas/rabbitmq-forge-boshrelease/blob/emit/jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml#L116)

2022-06-10 14:15 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/spec
> +    description: The private key for metrics emitter
Actually we don't, at least on in this context and was removed. This was added in the beginning of the process and got replaced by a better named key, loggregator

2022-06-10 14:20 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/spec
> +  rabbitmq_metrics_emitter.cloud_foundry.api:
because it falls under the `rabbitmq_metrics_emitter` release instead of the `rabbitmq` release

2022-06-10 14:22 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/spec
> +  blacksmith_rabbitmq_services.tls.ca_cert:
as per the comment above, this was removed so no longer applicable

2022-06-10 14:26 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +    password:   <%= p('cf.password') %>
given the different stages of how the manifest is rendered we can't. We ought to provide these values while the instance is created whereas the file is created after the instance gets fired up... which means to say that, we might as well remove the `meta.yml`

2022-06-10 14:29 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +- name: rabbitmq_standalone_crt
We could, though we do have two distinct types of services - standalone *and* cluster. The idea behind it is to differentiate between the two, especially early on the testing creation process, and could assist in later troubleshooting sessions

2022-06-10 14:32 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +          ca: (( file "/var/vcap/jobs/blacksmith/config/tls/blacksmith_services_ca" ))
it was put there to allow that exactly. Using a `file` pointer idea in general was "stolen" from other manifests...

2022-06-10 14:33 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +          key: ((rabbitmq_standalone_crt.private_key))
same answer as above... wdyt?

2022-06-10 14:35 UTC, itsouvalas commented on jobs/rabbitmq-blacksmith-plans/templates/tls/blacksmith_rabbitmq_services.ca
> +<%= p('blacksmith_rabbitmq_services.tls.ca_cert') %>
removed as above

2022-06-10 17:33 UTC, wayneeseguin commented on jobs/rabbitmq-blacksmith-plans/templates/plans/standalone/manifest.yml
> +- name: rabbitmq_standalone_crt
I get the logic, I'm just not clear on how it would be useful in debugging as the bound SI endpoint would be clear if it was a standalone or cluster. Leaving for now.

2022-06-10 17:33 UTC, merged